import { useState } from "react";
import { ChevronDown, ChevronUp } from "lucide-react";

import { MemoryJournal } from "./MemoryJournal.jsx";

export function MyJapanSection({C,summary,onResolveTrip,onMemoryPhoto,onMemoryNote,getMemoryPhotoUrl,syncStatus,onSyncNow}) {
  const [openTrip,setOpenTrip]=useState(null);
  const stats=[[summary.completedTrips,"voyages"],[summary.completedDays,"jours avec activité"],[summary.visitedPlaces,"lieux faits"],[summary.visitedCities,"villes"],[summary.visitedRegions,"régions"],[summary.stamps.length,"tampons"]];
  return <section aria-labelledby="my-japan-title" style={{marginBottom:18}}>
    <div style={{display:"flex",justifyContent:"space-between",alignItems:"baseline",marginBottom:10}}><h2 id="my-japan-title" style={{fontSize:16,color:C.text,margin:0,fontFamily:"'Noto Serif JP',serif"}}>Mon Japon</h2><span style={{fontSize:10,color:C.t3}}>Données vérifiées</span></div>
    <div style={{padding:14,background:C.s1,border:`1px solid ${C.border}`,borderRadius:18,boxShadow:C.shadow}}>
      {syncStatus&&<div style={{display:"flex",alignItems:"center",gap:9,padding:"10px 11px",marginBottom:12,borderRadius:12,background:C.s2}}><span aria-hidden style={{width:8,height:8,borderRadius:"50%",background:syncStatus.hasError?C.red:syncStatus.pending?C.gold:C.green}}/><div style={{flex:1,minWidth:0}}><div style={{fontSize:11,fontWeight:650,color:C.text}}>{syncStatus.hasError?"Synchronisation interrompue":syncStatus.pending?`${syncStatus.pending} élément${syncStatus.pending>1?"s":""} à synchroniser`:"Sauvegarde cloud à jour"}</div><div style={{fontSize:9,color:C.t3,marginTop:2}}>{syncStatus.lastSyncedAt?`Dernière sauvegarde ${new Date(syncStatus.lastSyncedAt).toLocaleString("fr-FR")}`:"Première sauvegarde en attente"}</div></div>{syncStatus.pending>0&&<button onClick={onSyncNow} style={{border:0,borderRadius:9,padding:"7px 9px",background:C.s1,color:C.red,fontSize:10}}>Réessayer</button>}</div>}
      {summary.awaitingConfirmation.length>0&&<div style={{padding:13,marginBottom:12,borderRadius:14,background:`${C.gold}12`,border:`1px solid ${C.gold}40`}}><div style={{fontSize:12,fontWeight:700,color:C.text,marginBottom:4}}>Voyage à confirmer</div><div style={{fontSize:10,color:C.t2,lineHeight:1.5,marginBottom:10}}>Une date passée ne suffit pas pour compter un voyage comme vécu.</div>{summary.awaitingConfirmation.map(trip=><div key={trip.id} style={{paddingTop:9,borderTop:`1px solid ${C.border}`}}><div style={{fontSize:12,color:C.text,fontWeight:600}}>{trip.title}</div><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:7,marginTop:8}}><button onClick={()=>onResolveTrip?.(trip.id,true)} style={{padding:9,border:0,borderRadius:10,background:C.green,color:"#fff",fontSize:11}}>Oui, effectué</button><button onClick={()=>onResolveTrip?.(trip.id,false)} style={{padding:9,border:`1px solid ${C.border}`,borderRadius:10,background:C.s1,color:C.t2,fontSize:11}}>Non / annulé</button></div></div>)}</div>}
      <div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:8,textAlign:"center"}}>{stats.map(([value,label])=><div key={label} style={{padding:"10px 4px",background:C.s2,borderRadius:12}}><div style={{fontSize:18,fontWeight:750,color:C.text}}>{value}</div><div style={{fontSize:9,color:C.t3,marginTop:2}}>{label}</div></div>)}</div>
      {summary.regionNames.length>0&&<div style={{display:"flex",gap:6,flexWrap:"wrap",marginTop:12}}>{summary.regionNames.map(region=><span key={region} style={{padding:"4px 9px",fontSize:10,color:C.t2,background:C.s2,borderRadius:99}}>{region}</span>)}</div>}
      {summary.stamps.length>0&&<><div style={{fontSize:10,fontWeight:700,color:C.t3,letterSpacing:".12em",marginTop:16,marginBottom:9}}>PASSEPORT</div><div style={{display:"flex",gap:9,overflowX:"auto",paddingBottom:4}}>{summary.stamps.map(stamp=><div key={stamp.id} style={{flexShrink:0,width:72,textAlign:"center"}}><div style={{width:54,height:54,margin:"0 auto 5px",borderRadius:"50%",border:`2px dashed ${C.red}`,background:`${C.red}10`,display:"flex",alignItems:"center",justifyContent:"center",fontSize:25}}>{stamp.emoji}</div><div style={{fontSize:9,color:C.t2,lineHeight:1.25}}>{stamp.label}</div></div>)}</div></>}
      {summary.collections?.length>0&&<><div style={{fontSize:10,fontWeight:700,color:C.t3,letterSpacing:".12em",marginTop:17,marginBottom:8}}>COLLECTIONS</div><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:8}}>{summary.collections.map(collection=><div key={collection.id} style={{padding:12,borderRadius:14,background:`linear-gradient(145deg,${C.s2},${C.s1})`,border:`1px solid ${C.border}`,display:"flex",alignItems:"center",gap:10}}><span style={{fontSize:24}}>{collection.emoji}</span><span><strong style={{display:"block",fontSize:16,color:C.text}}>{collection.count}{collection.total?` / ${collection.total}`:""}</strong><span style={{fontSize:10,color:C.t3}}>{collection.label}</span></span></div>)}</div></>}
      {summary.completedTripDetails.length>0&&<><div style={{fontSize:10,fontWeight:700,color:C.t3,letterSpacing:".12em",marginTop:17,marginBottom:8}}>VOYAGES PASSÉS</div>{summary.completedTripDetails.map(trip=>{const open=openTrip===trip.id;return <div key={trip.id} style={{borderTop:`1px solid ${C.border}`,padding:"11px 2px"}}><button onClick={()=>setOpenTrip(open?null:trip.id)} style={{width:"100%",display:"flex",alignItems:"center",gap:10,border:0,background:"transparent",color:C.text,textAlign:"left",padding:0}}><span style={{fontSize:21}}>🗾</span><span style={{flex:1}}><span style={{display:"block",fontSize:13,fontWeight:650}}>{trip.title}</span><span style={{display:"block",fontSize:10,color:C.t3,marginTop:2}}>{trip.days} jours · {trip.completedPlaces} lieux réalisés{trip.notes?` · ${trip.notes} notes`:""}</span></span>{open?<ChevronUp size={17}/>:<ChevronDown size={17}/>}</button>{open&&<div style={{padding:"10px 0 0 31px"}}>{trip.cities.length>0&&<div style={{display:"flex",gap:5,flexWrap:"wrap",marginBottom:8}}>{trip.cities.map(city=><span key={city.id} style={{fontSize:10,color:C.t2}}>{city.emoji} {city.name}</span>)}</div>}{trip.places.length>0?<div style={{fontSize:11,color:C.t2,lineHeight:1.7}}>{trip.places.map(place=><div key={place.id}>{place.emoji} {place.name}</div>)}</div>:<div style={{fontSize:11,color:C.t3}}>Aucun lieu n’avait été marqué comme fait.</div>}</div>}</div>})}</>}
      <MemoryJournal C={C} memories={summary.memories} getPhotoUrl={getMemoryPhotoUrl} onPhoto={onMemoryPhoto} onNote={onMemoryNote}/>
      {summary.visitedPlaces===0&&<div style={{fontSize:11,color:C.t3,lineHeight:1.5,marginTop:11,textAlign:"center"}}>Marque un lieu comme fait dans une journée pour commencer ton passeport.</div>}
    </div>
  </section>;
}
