-- Registre minimal des appels IA facturables. Les utilisateurs peuvent lire et
-- créer leurs propres lignes, mais jamais les modifier/supprimer pour contourner
-- les quotas. La fonction Edge réserve une ligne juste avant l'appel fournisseur.
create table if not exists public.ai_usage (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  feature text not null check (feature in ('itinerary')),
  created_at timestamptz not null default now()
);

create index if not exists ai_usage_user_feature_created_idx
  on public.ai_usage (user_id, feature, created_at desc);

alter table public.ai_usage enable row level security;

create policy "Users read own AI usage" on public.ai_usage
  for select using (auth.uid() = user_id);

-- Réservation atomique : le verrou par utilisateur+fonction empêche une rafale
-- parallèle de lire le même compteur avant les insertions concurrentes.
create or replace function public.reserve_ai_usage(p_feature text, p_daily_limit int, p_monthly_limit int)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  uid uuid := auth.uid();
  daily_used int;
  monthly_used int;
begin
  if uid is null or p_feature <> 'itinerary' then raise exception 'not_allowed'; end if;
  perform pg_advisory_xact_lock(hashtextextended(uid::text || ':' || p_feature, 0));
  select count(*) into daily_used from public.ai_usage where user_id=uid and feature=p_feature and created_at>=date_trunc('day',now() at time zone 'utc');
  select count(*) into monthly_used from public.ai_usage where user_id=uid and feature=p_feature and created_at>=date_trunc('month',now() at time zone 'utc');
  if daily_used>=p_daily_limit or monthly_used>=p_monthly_limit then
    return jsonb_build_object('allowed',false,'dailyUsed',daily_used,'dailyLimit',p_daily_limit,'monthlyUsed',monthly_used,'monthlyLimit',p_monthly_limit);
  end if;
  insert into public.ai_usage(user_id,feature) values(uid,p_feature);
  return jsonb_build_object('allowed',true,'dailyUsed',daily_used+1,'dailyLimit',p_daily_limit,'monthlyUsed',monthly_used+1,'monthlyLimit',p_monthly_limit);
end;
$$;

revoke all on function public.reserve_ai_usage(text,int,int) from public;
grant execute on function public.reserve_ai_usage(text,int,int) to authenticated;
